apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stanovanjske-zadruge-zemljevid
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - frontend.yaml
images:
  - name: stanovanjske-zadruge-zemljevid
    newName: rg.fr-par.scw.cloud/djnd/stanovanjske-zadruge-zemljevid
    newTag: '3d9f7164ae885669226560e09256289b73a9c99c'
  - name: stanovanjske-zadruge-zemljevid-frontend
    newName: rg.fr-par.scw.cloud/djnd/stanovanjske-zadruge-zemljevid-frontend
    newTag: '3d9f7164ae885669226560e09256289b73a9c99c'
