apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stanovanjske-zadruge-zemljevid
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - frontend.yaml
images:
  - name: stanovanjske-zadruge-zemljevid
    newName: rg.fr-par.scw.cloud/djnd/stanovanjske-zadruge-zemljevid
    newTag: 'fc9c9aeab969e1ae27932755cdb490d289847804'
  - name: stanovanjske-zadruge-zemljevid-frontend
    newName: rg.fr-par.scw.cloud/djnd/stanovanjske-zadruge-zemljevid-frontend
    newTag: 'fc9c9aeab969e1ae27932755cdb490d289847804'
