apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stanovanjske-zadruge-zemljevid
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - frontend.yaml
images:
  - name: stanovanjske-zadruge-zemljevid
    newName: rg.fr-par.scw.cloud/djnd/stanovanjske-zadruge-zemljevid
    newTag: '1f6366a8a064ab9a0b48fdca2ac0c225b41c0366'
  - name: stanovanjske-zadruge-zemljevid-frontend
    newName: rg.fr-par.scw.cloud/djnd/stanovanjske-zadruge-zemljevid-frontend
    newTag: '1f6366a8a064ab9a0b48fdca2ac0c225b41c0366'
