apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stanovanjske-zadruge-zemljevid
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - frontend.yaml
images:
  - name: stanovanjske-zadruge-zemljevid
    newName: rg.fr-par.scw.cloud/djnd/stanovanjske-zadruge-zemljevid
    newTag: 'a87e7847addc3497877eeac7046045df70c67fbb'
  - name: stanovanjske-zadruge-zemljevid-frontend
    newName: rg.fr-par.scw.cloud/djnd/stanovanjske-zadruge-zemljevid-frontend
    newTag: 'a87e7847addc3497877eeac7046045df70c67fbb'
