apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stanovanjske-zadruge-zemljevid
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - frontend.yaml
images:
  - name: stanovanjske-zadruge-zemljevid
    newName: rg.fr-par.scw.cloud/djnd/stanovanjske-zadruge-zemljevid
    newTag: '118c9a377a6057f1725347e55c93c589c328193a'
  - name: stanovanjske-zadruge-zemljevid-frontend
    newName: rg.fr-par.scw.cloud/djnd/stanovanjske-zadruge-zemljevid-frontend
    newTag: '118c9a377a6057f1725347e55c93c589c328193a'
