# Generated by Django 3.2.7 on 2022-02-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_token_used_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='admin_token',
            field=models.BooleanField(default=False),
        ),
    ]
